server:
  host: 0.0.0.0
  port: 8080
  read_timeout: 15
  write_timeout: 15
  idle_timeout: 60

php:
  enabled: true
  binary: /usr/bin/php-cgi
  workers: 10
  max_execution_time: 30

paths:
  document_root: ./public
  log_file: ./logs/server.log

security:
  tls:
    enabled: false
    cert_file: ./certs/cert.pem
    key_file: ./certs/key.pem
  cors:
    enabled: true
    allowed_origins: ["*"]
    allowed_methods: ["GET", "POST", "OPTIONS"]
  rate_limit:
    enabled: true
    requests_per_minute: 60
  headers:
    x_content_type_options: nosniff
    x_frame_options: SAMEORIGIN
    content_security_policy: "default-src 'self' 'unsafe-inline'"
    strict_transport_security: "max-age=31536000; includeSubDomains"